apiVersion: v1
kind: Service
metadata:
  name: monitoring-env-svc
spec:
  type: NodePort
  selector:
    pod: prom-graf-pod

  ports:
  - port: 9090
    protocol: TCP
    name: prom-port
  - port: 3000
    protocol: TCP
    name: graf-port
